/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p cluster_interface /home/shanmugapriyan/Documents/Sim/QtTest/myservice.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "cluster_interface.h"

/*
 * Implementation of interface class ExperionServerDbusInterface
 */

ExperionServerDbusInterface::ExperionServerDbusInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ExperionServerDbusInterface::~ExperionServerDbusInterface()
{
}


#include "moc_cluster_interface.cpp"
